apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: endpoint-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header Set-Cookie "Canary=always; Path=/";
spec:
  rules:
  - host: endpoint.app.microfrontend
    http:
      paths:
        - backend:
            serviceName: endpoint-svc
            servicePort: 2222
