apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: endpoint-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # nginx.ingress.kubernetes.io/configuration-snippet: |
      # add_header Set-Cookie "Canary=always; Path=/namespace/endpoint";

    # https://stackoverflow.com/questions/26189429/how-to-debug-lua-code-inside-nginx-config
    # nginx.ingress.kubernetes.io/server-snippet: |
    #   rewrite_by_lua_block {
    #     ngx.req.set_header("X-Please-Work", "does it")
    #     ngx.log(ngx.STDERR, "your message here")
    #     print("is this working?")
    #     ngx.say("hello")
    #     ngx.res.set_header("X-Please-Work", "does it")
    #     math.randomseed(1)
    #     nvx.var.random_num = math.random(0,3)
    #   }
spec:
  rules:
  - host: app.microfrontend
    http:
      paths:
        - path: /namespace/endpoint/?(.*)
          backend:
            serviceName: endpoint-svc
            servicePort: 2222
