const { minikubeKubectl }  = require('./utils');


updateTrafficPercentage()

async function updateTrafficPercentage() {
    const chanceToGoToCanary = parseFloat(process.argv[2]);

    if (isNaN(chanceToGoToCanary) || chanceToGoToCanary < 0 || chanceToGoToCanary > 1) {
        throw new Error('Invalid Input: chanceToGoToCanary must be between 0 and 1');
    }

    // This configmap is generated by the minikube ingress addon
    // TODO: Test on linux
    await minikubeKubectl(`patch configmap nginx-load-balancer-conf -n kube-system --type json -p '[{ \\"op\\": \\"replace\\", \\"path\\": \\"/data/server-snippet\\", \\"value\\": \\" set_by_lua_block $chanceToGoToCanary { return ${chanceToGoToCanary} }\\" }]'`);

    console.log(`Chance to go to canary changed to ${chanceToGoToCanary}`);
}
